[features]
seeds = false

[programs.devnet]
amm_v3 = "CnhWofYruFeG98WR13YZeuZwHbpEC8S1e2uC9MkcWon8"

[registry]
url = "https://github.com/raydium-io/raydium-amm-v3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json" 

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./external-programs/spl_token_metadata.so"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.27"